version: '3.1'

services:

  nginx-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    restart: always
    ports:
      - "80:80"

  mysql-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app-dev
    restart: always
    environment:
      - NODEJS_API_PORT=8080
      - NODE_DS=mysql-app
      - NODE_USER=notes_api
      - NODE_PASS=notes-api
    ports:
      - "8080:8080"    
